# Generated by Django 5.2.4 on 2025-08-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='cover_letter',
            field=models.FileField(upload_to='coverLetters', verbose_name='Cover Letter'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='resume',
            field=models.FileField(upload_to='resumes', verbose_name='Resume'),
        ),
    ]
