# Generated by Django 5.2.4 on 2025-08-12 08:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_jobs_cover_letter_alter_jobs_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='jobs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
