# Generated by Django 5.2.5 on 2025-08-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_last_updated_jobs_updated_at_jobs_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='cover_letter',
            field=models.FileField(blank=True, upload_to='coverLetters', verbose_name='Cover Letter'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='location',
            field=models.CharField(blank=True, max_length=300, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes', verbose_name='Resume'),
        ),
    ]
