# Generated by Django 5.2.5 on 2025-08-23 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_jobs_cover_letter_alter_jobs_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='interview_notes',
            new_name='notes',
        ),
    ]
