# Generated by Django 5.2.5 on 2025-08-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_interview_notes_jobs_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='notes',
            field=models.JSONField(blank=True, default=list, verbose_name='Notes'),
        ),
    ]
