# Generated by Django 5.2.5 on 2025-08-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_jobs_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='cover_letter',
            field=models.FileField(blank=True, upload_to='cover_letters/', verbose_name='Cover Letter'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes/', verbose_name='Resume'),
        ),
    ]
