# Generated by Django 5.2.5 on 2025-08-27 07:26

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_jobs_cover_letter_alter_jobs_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='cover_letter',
            field=models.FileField(blank=True, storage=storages.backends.s3.S3Storage(), upload_to='cover_letters/', verbose_name='Cover Letter'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='resume',
            field=models.FileField(blank=True, storage=storages.backends.s3.S3Storage(), upload_to='resumes/', verbose_name='Resume'),
        ),
    ]
