# Generated by Django 5.2.5 on 2025-09-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_jobs_cover_letter_alter_jobs_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='cover_letter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='resume_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='cover_letter',
            field=models.FileField(blank=True, upload_to='cover_letters/', verbose_name='Cover Letter'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes/', verbose_name='Resume'),
        ),
    ]
